//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package codec

/*
#cgo CFLAGS: -I${SRCDIR}/include -I${SRCDIR}/modules/platform/include -I${SRCDIR}/codec-c -I${SRCDIR}/modules/platform/src -I${SRCDIR}/modules/platform/third_party/gmp -I${SRCDIR}/modules/platform/third_party/mpfr/src -O2 -Wall -std=c11 -D_POSIX_C_SOURCE=200112L -mavx2 -mfma
#cgo LDFLAGS: ${SRCDIR}/modules/platform/build/linux_amd64/third_party/mpfr/libmpfr.a ${SRCDIR}/modules/platform/build/linux_amd64/third_party/gmp/libgmp.a -lm


#include "codec.h"
#include "fix_codec.h"

// Platform sources (dependency)
#include "simd_detect.c"
#include "fc_bignum_init.c"
#include "fc_bigint.c"
#include "fc_bigfloat.c"
#include "fc_precision.c"
#include "mem_aligned.c"
#include "error.c"
#include "fc_init.c"

// Platform-specific sources
#if defined(__linux__)
  #include "modules/platform/src/platform_linux.c"
#elif defined(__APPLE__)
  #include "modules/platform/src/platform_macos.c"
#elif defined(_WIN32)
  #include "modules/platform/src/platform_win.c"
#endif

// Codec sources
#include "codec-c/fix_codec.c"
*/
import "C"
